### ISSUE TITLE
Keyboard processing in SadConsole doesn't look for CAPSLOCK or NUMLOCK

### ISSUE THREAD

**Issue by SadConsole** [SadConsole/SadConsole#185]
Because of this, code slipped in to use the . numpad key as delete incorrectly: 
https://github.com/SadConsole/SadConsole/blob/develop-7.3/src/SadConsole.Shared/Controls/TextBox.cs#L360

`AsciiKey` should process the correct character based on NUMLOCK and CAPSLOCK states.

**Comment by darrellp** [comment]
I am sorry I left this in.  Put it in for debugging purposes because the keycode for "Delete" is not coming down correctly.  Ditto for "Home" and "End".  This should be changed in AsciiKey.Fill(), correct?  Again, my apologies.

**Comment by SadConsole** [comment]
Nah, it's OK. If you had not done that, I don't think I would have noticed that the keyboard implementation doesn't respect NUMLOCK problem in the first place 😄

**Comment by darrellp** [comment]
I've been looking into how to fix this.  That keyboard input is a bit of a rabbit hole.  Figured out how to get numlock/capslock key state and mostly fixed it in my version but I kinda don't trust myself in what I feel like is very fragile code.

**Comment by darrellp** [comment]
BTW – one of the responses here has XNA error handling which catches the “lock” states using Win32 calls:

https://www.gamedev.net/forums/topic/457783-xna-getting-text-from-keyboard/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SadConsole** [comment]
The way I figured to fix it was to append to the loop logic here: https://github.com/SadConsole/SadConsole/blob/develop-7.3/src/SadConsole.Shared/Input/Keyboard.cs#L122

This should detect those CAPS/NUMLOCK states and 

1. `AsciiKey.Fill` should have a change that accepts NUMLOCK bool along with the shift status.
1. if CAPS is pushed, set the shift flag sent to `AsciiKey.Fill`
2. if NUMLOCK is pushed, set the numlock flag sent to `AsciiKey.Fill`
3. `AsciiKey.Fill` should check if the combination of numlock is true and one of the keypad keys is set and change the current `Key` enum that is being sent to the appropriate value

Something like that.

**Comment by darrellp** [comment]
My first response was to change the entries in AsciiKey.FillKey() which was mostly working but the repeated key stuff failed.  As a consequence I think it’s probably better to prefilter the keys = state.GetPressedKeys() just before the loop you refer to.  Pretty amazing how little XNA/MonoGame gives you.  I assumed that the repeating keys would be automatic, but found out differently.  Did you do all that keyboard stuff from scratch or base it off something else?  Must have been a slog to get through.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by darrellp** [comment]
Oh – one other thing.  It’s mostly aesthetic, but it kind of drives me batty to see all those cases for all the alphabetic chars in FillKey which could all be replaced by an:
                If (key >= Keys.A && key <= Keys.Z)…
I’m loathe to make (or perhaps even suggest) the change because it’s unnecessary, but it would clear a lot of code away and in the interests of the “do everything only once” principle makes some sense.  Do you have objections?  All you’ve gotta say is “Shut up Darrell!  I like it that way!” and I will happily do exactly that.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SadConsole** [comment]
Yeah, I did all that by scratch. Crazy huh!? Sure! Make anything more efficient. When I'm going at something from scratch I just think it through. Oh I need a... b... c.. and don't think "Is that the best way?" Well I do more so now, but a lot of this code is 10 years old. While this project has been on github for the last 5 it was all private code prior 😄 

You can even use the new pattern matching of C# 7

```csharp
            switch (key)
            {
                case var key2 when key2 >= Keys.A && key2 <= Keys.Z:
                    if (shiftPressed)
                        Character = (char)key2;
                    else
                        Character = (char)(key2 + 32);
                    break;
```

**Comment by SadConsole** [comment]
No worries! I'm getting close to releasing v8. A few other things coming through.

**Comment by darrellp** [comment]
Okay, ready to do this.  Honestly, part of my reason for hesitation is I feel like I still don’t really understand the whole Git process for pull requests and I feel like I should so I’m a bit embarrassed to ask.  Once I feel comfortable with that I’ll be much happier.  To that end and exposing my regrettable ignorance, here’s what you told me last time which I wrote down carefully:


so your workflow would be

1. fetch from upstream (which points to sadconsole on github)

2. create a new branch based on one from upstream's branch

3. do your changes and makes commits

4. send your branch (with its commits) to YOUR github fork because you have permissions to do that

5. initiate a pull request from your github fork-branch to sadconsole github fork-branch

Okay – I’ve got a fork and I’ve got a local repository based on that fork.  I think step 1 above, fetch from upstream, is actually intended for my fork repository rather than my local one?  I think my fork certainly has to reflect the current state of SadConsole so I’m assuming that’s what is meant.  The trouble is I’m not sure whether I’m correct on that and if I am I’m not sure about how to go about doing it.  When I look at my local repository under remotes it says I have an “origin” which is my forked repo on Github and an “upstream” which is your SadConsole repo.  So the first order of business, I believe is step 1.  I noticed I could fetch locally from “upstream” rather than from origin.  I tried that thinking that there was a hint of a chance that it would fetch into the fork and then fetch down to me.  Didn’t seem to work.  Fork is still 29 commits behind.

So after I get step 1 figured out, I need to create a new branch.  I’m thinking again that you mean to create it in the fork repo rather than my local and then fetch that down to my local.  Once again, I’m not quite sure how to do that.  This all may be largely because I’ve been relying too heavily on the VS version of source control rather than just breaking down and doing everything by command line.  I’m starting to think that I’m never really going to get that until I start using the command line interface.

I’d go over to Discord to discuss but it looks like that’s been blocked?  Okay.  Sorry for all the handholding and thanks for your patience in this process.  I don’t seem to have grokked the team experience in Git yet.

Darrell

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by darrellp** [comment]
In researching this “sync my fork repository” business I came across the following page: https://help.github.com/articles/syncing-a-fork/
It says “before you can sync your fork with an upstream repository, you must configure a remote that points to the upstream repository<https://help.github.com/articles/configuring-a-remote-for-a-fork> in Git”.  So does that mean I need two local repos – one pointing at the upstream directory (i.e., you) and one pointing at my forked directory?  Or is this somehow one repo that points at both?  It seems like it when they talk about merging branches from the upstream to the branch.  I don’t know why this is so hard for me to get.  Usually the more I read the better informed I feel.  With Git I feel the opposite – the more I read the more confused I become.

Darrell

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SadConsole** [comment]
Sorry in the delay to getting back to you! No discord shouldn't be blocked. I think there were two darrellp accounts and I tried to get rid of one, but not like kick you out. What is your user#number? I'll make sure to just directly invite you

Everyone is GitShy at first 😄 I've helped tons of people at work and elsewhere learn how to do this stuff. Don't worry! **everyone** is confused by git. 

So the first set of steps you listed are correct. What I do at work in this same situation is 

upstream = main work github repo
origin = my github repo

1. `git checkout <branch>`  
**master** or whatever branch you know you're working with, so like **develop-8.0** if you're working on the latest

2. `git pull --rebase upstream <branch>`  
this does a fetch, pull, and keeps things clean and matching (if you've never edited anything in your local copy of the branch

3.`git checkout -b <your-new-branch-name>`
this creates a copy of the current branch into a new branch name (generally named something around your feature you're working on)

4. Do all your changes, commits, etc
5. `git push origin <branch>`  
this sends your branch (as long as the name on the command line is the same as the branch you have checkedout, this works fine) to your account in github

6. Submit your PR
7. Any changes that need to be made, do steps 4 and 5 again
7. When PR is merged and accepted. Go back to your command line and start at step 1 again

**Comment by darrellp** [comment]
Hey Andy –

Doing stuff on the keyboard.  There’s some twisted code in there.  Cleaned up the big switch in AsciiKey and CapsLock is working.  NumLock I think might be tougher.  A big assumption right now is that the characters that share keys are fixed in stone.  I think that’s correct on the main keyboard which is why I think I got CapsLock working correctly.  I’m not so sure of this on the Number pads where I think keyboards sometimes disagree.  I think getting it working on MY keyboard (which I think is pretty standard) will not be too awfully difficult but I’m not so sure about how it’s gonna pan out on other keyboards.  Having worked in this stuff before, do you have any info on that?  I’m gonna start researching but haven’t dug anything up yet.

Darrell
