### ISSUE TITLE
Core Framework Architecture

### ISSUE THREAD

**Issue by erictuvesson** [SadConsole/SadConsole#190]
Hey @Thraka,

I noticed that you posted some here https://github.com/mellinoe/veldrid/issues/79. I was really interested to see if I could get it working, but I find the code architecture to be a little confusing and I am getting a feeling that it is not very good for supporting multiple frameworks. 

Would it be possible to split the core framework code from the project without to much harm? Like the window, input and graphics.

**Comment by Thraka** [comment]
No, it wasn't designed to be portable and has a hard dependency on MonoGame. I have done some work to try and get all the startup/init code specific to MonoGame out into the `Graphics.MonoGame` namespace. 

1. Everything uses `Rectangle` and `Point` a lot. 
1. `Font` uses `Texture2d`
1. Base surface class uses a `RenderTarget` 
1. `Input` stuff is obviously MonoGame specific, but just in mouse/keyboard polling and for the keyboard `AsciiKey` type
1. The [SadConsoleGameComponent](https://github.com/SadConsole/SadConsole/blob/master/src/SadConsole.Shared/Graphics.MonoGame/SadConsoleGameComponent.cs) is the main game loop that through `Update` does the input and processes the `Update` on all the child game objects. `Draw` calls the draw on all child game objects which builds the `Global.DrawCalls` and then renders the game screen.

Apart from those basic things, there isn't much else that is MonoGame specific. So really to draw, just need

- Rectangle
- Point
- Texture
- SpriteBatching for drawing
- RenderTargets

**Comment by erictuvesson** [comment]
I currently only have my macbook with me so it's hard to make big changes especially when you can't get something running, I would really like to take a deeper look at it next week thought! One good way to handle all the different platforms is to have partial classes and split it up that way without changing everything. 

Things like Rectangle, Point, Texture can be the same so could technically the SpriteBatch be as well. The only downside to having it completely the same could be that there is possibility of improvements which SpriteBatch wouldn't be able to handle without some changes. It's up to you what you think the best way would be.

_I have noticed that that there is a heavy use of static variables, I am personally not a big fan of that._ 🤔

**Comment by Thraka** [comment]
It's hard to support different frameworks because of those primitive types. Some issues I ran into while supporting both SFML and MonoGame. These may not be exact issues, just paraphrased to the type of thing I ran into:

1. SFML has a `Rect` type instead of `Rectangle` so I used `#if` with `using` to map the type name to the same as the other.
2. MonoGame has a lot of helper methods for primitive types and operator overloads that we can't replicate with extension methods. We need things like proposed for C# 9 with extension properties and extension operators.
3. Getting around 1 and 2 required a lot of `#if` statements and made the code hard to maintain.

There is heavy use of static for Global, yes. This is because I wanted the framework to be easily accessible  to newer programmers and also have an easy time learning how to make a game. While it's not ideal, **it's also not bad**. It does restrict you with unit testing and multithreading though. I don't mind changing this in the future, but I want to make sure it's still easy to use.

**Comment by erictuvesson** [comment]
Is there any special reason why the Xna/MonoGame version is using DrawableGameComponent's to rendering everything? 

I would like to create an abstract class that works like the Game class, I don't want to break the current API so would create a new class. I just want to move more and more away from the static properties, but still support the current API, doing this would also allow for multiple game windows.

**Comment by Thraka** [comment]
By using the DrawableGameComponent, it made it easy for those that know MonoGame/Xna style programming to add support to their game class and bypass all of the init and handholding SadConsole does by default. 

So for example I was playing around with a WPF app that had a monogame game running and I could easily do my own init code (since the environment was different than that a normal SadConsole game) and run the game component in the custom game. This let me render to a control on the WPF form.

The game class from MonoGame really handles the following:

1. Setting up the window
2. Calling update/draw loops
3. Providing a spot to load resources
4. Composable via the GameComponents that hook into update/draw loops automatically (though I never really used this, I just did in this case because it made sense for using SadConsole to say render on a 3d computer screen inside your already made monogame game)
5. Unloading all your stuff

**Comment by SadConsole** [comment]
Considering v9 has already split this out, I'm going to close this.
