### ISSUE TITLE
Generating a new font image with extended characters

### ISSUE THREAD

**Issue by nightblade9** [SadConsole/SadConsole#214]
How can I create a font file that supports ASCII character 186 (`║`)?

Assume I know nothing about the MonoGame content pipeline and `.font` files (that isn't far from the truth).

**Comment by Thraka** [comment]
Does https://sadconsole.com/articles/basic-font-information.html help?

**Comment by nightblade9** [comment]
That doesn't really help. I understand how the image file works, but not how to generate a new one.

The call to `FontMaster.Generate` looks promising, but I don't quite know if it's right or wrong: https://sadconsole.com/api/SadConsole.FontMaster.html#SadConsole_FontMaster_Generate

TL;DR how do I generate a new PNG for a new font/size/character-set?

**Comment by nightblade9** [comment]
Sorry, maybe I'm misunderstanding something. I'm going to close this and open another defect that describes exactly my problem instead of guessing what the solution is.

**Comment by SadConsole** [comment]
OHHH I see what you're asking. No, SadConsole doesn't generate font graphic files for you. You have to use a tool or a graphic editor to do that

**Comment by nightblade9** [comment]
If I wanted to do this, what tools could I use? Or do I have to do this by hand using any graphics manipulation tool?

**Comment by SadConsole** [comment]
I know there are lots of tools you can use to varying degrees. I just can't recommend any because I've never really used them. I'm pretty sure if you search/ask on https://www.reddit.com/r/roguelikedev/ you'll get some good answers.

However, if this is related to your other question, this isn't the way to solve the problem :) the tileset already supports character 186 but you were trying to inject a unicode version through a string, which your editor is forcing.

**Comment by nightblade9** [comment]
It was related to my real question, until I saw it in the chart. I will keep this in mind for future needs - thanks.
